### ISSUE TITLE
WindowsPhone 8.1 DeviceInfo.getHardware "Platform implementation not found.  Have you added a nuget reference to your platform project?"

### ISSUE THREAD

**Issue by jasonCodesAway** [aritchie/deviceinfo#10]
Hello,

Thank you for putting together this great library and nuget package. Unfortunately I have hit an issue when trying to use it. I've [attached](https://github.com/aritchie/deviceinfo/files/200861/WpAppDeviceInfoTest.zip) the simplest possible repro: a blank template windows phone 8.1 app with Acr.DeviceInfo (latest version, 4.0.30319) added and the below Debug.WriteLine:

```
public MainPage()
{
    this.InitializeComponent();
    Debug.WriteLine(Acr.DeviceInfo.DeviceInfo.Hardware.ScreenHeight);
    this.NavigationCacheMode = NavigationCacheMode.Required;
}
```

That Debug.WriteLine causes this:

```
System.Exception was unhandled by user code
  HResult=-2146233088
  Message=Platform implementation not found.  Have you added a nuget reference to your platform project?
  Source=Acr.DeviceInfo
  StackTrace:
       at Acr.DeviceInfo.DeviceInfo.<>c.<.cctor>b__20_3()
       at System.Lazy`1.CreateValue()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Lazy`1.get_Value()
       at Acr.DeviceInfo.DeviceInfo.get_Hardware()
       at WpAppDeviceInfoTest.MainPage..ctor()
       at WpAppDeviceInfoTest.WpAppDeviceInfoTest_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage()
       at WpAppDeviceInfoTest.WpAppDeviceInfoTest_XamlTypeInfo.XamlUserType.ActivateInstance()
  InnerException: 
```

I have tested using the "Emulator 8.1 WVGA 4 inch 512MB" in case that makes a difference. What am I missing? Or is this a bug?

Thank You!

Cheers from Florida,
Jason

**Comment by aritchie** [comment]
Hi Jason.  I added winphone support request last year as a request but I can't stand it as a platform so I'm dropping it in the very near future.  UWP will be the only windows support going forward.

**Comment by jasonCodesAway** [comment]
Hi Aritchie,

Any way I can offer you some beer money to reconsider!? I feel your pain with WP8.1 but please do consider that it's a damn fast emulator for Visual Studio which enables rapid development. Unfortunately many libraries and tools don't yet support UWP. If you still choose to drop WP8.1 I completely understand. Thanks for the quick response!

Cheers,
Jason
