### ISSUE TITLE
ScreenWidth and ScreenHeight return different values depending on orientation on Androi

### ISSUE THREAD

**Issue by JKennedy24** [aritchie/deviceinfo#11]
This affects devices with soft back buttons at the bottom of the android device. From what I can see this is to do with the displaymetrics returning different HeightPixels and WidthPixels depending on orientation.

And I'm not talking about the obvious swapping of the values I mean

Portrait: 976 x 768
Landscape: 1024 x 720

**Comment by JKennedy24** [comment]
need to use GetRealMetrics() rather than DisplayMetrics. More information found: http://stackoverflow.com/questions/6520718/how-to-get-screen-width-and-height

**Comment by lichfn** [comment]
Hello,
I encountered the same issue on android, will this be fixed soon ?
Thanks

**Comment by aritchie** [comment]
If you need something fixed on a timeline, why not contribute a pull request?

**Comment by lichfn** [comment]
I'm a student I don't know much c# :( I'm sorry

**Comment by aritchie** [comment]
This should be fixed up in v4.0.0-beta1.  Please give it a try and send some feedback
