### ISSUE TITLE
DeviceInfo.App.Version Throws exceptions on iOS and UWP

### ISSUE THREAD

**Issue by JKennedy24** [aritchie/deviceinfo#12]
Exceptions being thrown on iOS and UWP when calling

Acr.DeviceInfo.App.Version

**Comment by aritchie** [comment]
Please include the exception!

**Comment by JKennedy24** [comment]
@aritchie 
The exception being thrown is:

> Delegate to an instance method cannot have null 'this'.
> 
>    at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
>    at Acr.DeviceInfo.AppImpl..ctor()
>    at Acr.DeviceInfo.DeviceInfo.<>c.<.cctor>b__20_0()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at System.Lazy`1.get_Value()
>    at Acr.DeviceInfo.DeviceInfo.get_App()
>    at FieldStrikeMove.PortableData.Data.SyncHandlers.DataSync.StartSync(Dictionary`2 parameters)

**Comment by aritchie** [comment]
I have not been able to reproduce this.  What version of the plugin is this?  Does it happen to you when running the samples?
