### ISSUE TITLE
UWP: requesting hardware information hangs

### ISSUE THREAD

**Issue by blocksninja** [aritchie/deviceinfo#13]
When using a property from the Hardware class the application hangs.
I've tested with the Sample app for UWP, and it's reproducable there too.
It has to do with the request for getting VideoCapture 
After the following line it doesn't go any further:
`var list = await DeviceInformation.FindAllAsync(DeviceClass.VideoCapture);`
I've tried to find a solution, but did not succeed. UWP is new for me.

**Comment by aritchie** [comment]
This is fixed in v4.0
