### ISSUE TITLE
Bug in Connectivity for both UWP and WinPhone

### ISSUE THREAD

**Issue by ThumbGen** [aritchie/deviceinfo#14]
Hi

I might be wrong but there's a bug in the connectivity implementation for both Windows platforms:

var avail = NetworkInterface.GetIsNetworkAvailable();

```
        if (avail)
            this.InternetReachability = ConnectionStatus.NotReachable;
        else { ....
```

If the network is available the InternetReachability will be always NotReachable.....

**Comment by aritchie** [comment]
This is fixed in v4-beta1.  Give it a try on nuget
