### ISSUE TITLE
Could not load assembly System.Reactive.Linq (after update to 4.0.0)

### ISSUE THREAD

**Issue by davidtavarez** [aritchie/deviceinfo#15]
> Adding assembly reference for Acr.DeviceInfo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, recursively...
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Reactive.Linq, Version=2.2.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Perhaps it doesn't exist in the Mono for Android profile?
> File name: 'System.Reactive.Linq.dll'
>   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) <0x416fa80 + 0x00423> in <filename unknown>:0 
>   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference) <0x41b9330 + 0x0001f> in <filename unknown>:0 
>   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences (ICollection`1 assemblies, Mono.Cecil.AssemblyDefinition assembly, Boolean topLevel) <0x41b89f8 + 0x0046b> in <filename unknown>:0 
>   at Xamarin.Android.Tasks.ResolveAssemblies.Execute () <0x41b7e38 + 0x00577> in <filename unknown>:0 
>   Task "ResolveAssemblies" execution -- FAILED
>   Done building target "_ResolveAssemblies" in project "/Users/davidtavarez/Projects/WebOfertas/Droid/WebOfertas.Droid.csproj".-- FAILED

**Comment by se** [comment]
+1 Same problem for me. Is there any fix for it? kind of urgent to us :)

Thank you!

**Comment by aritchie** [comment]
Hmmm forgot the dependency in the nuspec.  Updating now
