### ISSUE TITLE
ios 10 issue with "rights"

### ISSUE THREAD

**Issue by softlion** [aritchie/deviceinfo#17]
On ios 10, if you use the deviceinfo nuget and publish your app on app store, you must add specific entries in info.plist to explain to Apple why you use features like bluetooth and camera. Even if you don't use them. Because the acr library uses them and full linking does not throw this part of code away.

Full linking should be able to find out that this code is not used by the app. So we should be able to publish an app using this nuget without having to add fake entries to info.plist, as some day in the future the submission might be refused by apple.

Another solution would be to split the nuget in pieces.

**Comment by aritchie** [comment]
So I have released with this package before with Apple saying anything.  Though these methods have proved utterly useless so I'll think about removing them in the near future

**Comment by softlion** [comment]
Nice !
