### ISSUE TITLE
Suggetion: Getting a list of WiFi devices avalible.

### ISSUE THREAD

**Issue by jsndk** [aritchie/deviceinfo#20]
Did not know where to put a suggestion sorry. 

Motivation for enhancement:
Reason is to be aware of where the device is. Getting a list of WiFi access point's including MAC address or similar. eg. not connect to them, just getting a list. returning a Enum of sorts. Same thing for BT devices. 

If a access point with name/MAC xxxxxxx is in the list, then the device is close to home/office and actions can be taken.

To be used with a background App. 

Regards
Jesper

**Comment by aritchie** [comment]
Thank you for the suggestion. This would only be workable in Android & UWP though.  In iOS, there is no way to accomplish this.  I'd welcome a PR for this.

For Bluetooth (at least LE), you can use my other library: https://github.com/aritchie/bluetoothle
