### ISSUE TITLE
Exception - [deviceinfo] Platform implementation not found

### ISSUE THREAD

**Issue by tangogrowler** [aritchie/deviceinfo#22]
Hi. I've just installed Acr.DeviceInfo.4.0.2 from NuGet to all my xamarin forms (2.3.3.180) projects (incl PCL).

I'm trying to access screensize via **Acr.DeviceInfo.DeviceInfo.Hardware.ScreenHeight**

But whether I call it from my WinPhone proj (App.xaml.cs OnLaunched()) or in the PCL (App.xaml.cs OnStart()) , I get the same error:

"An exception of type 'System.Exception' occurred in mscorlib.ni.dll but was not handled in user code
Additional information: [deviceinfo] Platform implementation not found.  Have you added a nuget reference to your platform project?"

**PCL StackTrace:**
   at Acr.DeviceInfo.DeviceInfo.<>c.<.cctor>b__21_3()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.get_Value()
   at Acr.DeviceInfo.DeviceInfo.get_Hardware()

**WinPhone StackTrace:**
   at Acr.DeviceInfo.DeviceInfo.<>c.<.cctor>b__21_3()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Acr.DeviceInfo.DeviceInfo.get_Hardware()
   at xxx.WinPhone.App.OnLaunched(LaunchActivatedEventArgs e)

I'm running in Debug on a WinPhone running Windows10. 

Any ideas?

Thanks
Gary

**PM Logs**
PM> Install-Package Acr.DeviceInfo
Attempting to gather dependency information for package 'Acr.DeviceInfo.4.0.2' with respect to project 'xxx.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Attempting to resolve dependencies for package 'Acr.DeviceInfo.4.0.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Acr.DeviceInfo.4.0.2'
Resolved actions to install package 'Acr.DeviceInfo.4.0.2'
  GET https://api.nuget.org/packages/rx-interfaces.2.2.5.nupkg
  OK https://api.nuget.org/packages/rx-interfaces.2.2.5.nupkg 17ms
Installing Rx-Interfaces 2.2.5.
Adding package 'Rx-Interfaces.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Interfaces.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Interfaces.2.2.5' to 'packages.config'
Successfully installed 'Rx-Interfaces 2.2.5' to xxx.iOS
  GET https://api.nuget.org/packages/rx-core.2.2.5.nupkg
  OK https://api.nuget.org/packages/rx-core.2.2.5.nupkg 16ms
Installing Rx-Core 2.2.5.
Adding package 'Rx-Core.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Core.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Core.2.2.5' to 'packages.config'
Successfully installed 'Rx-Core 2.2.5' to xxx.iOS
  GET https://api.nuget.org/packages/rx-linq.2.2.5.nupkg
  OK https://api.nuget.org/packages/rx-linq.2.2.5.nupkg 18ms
Installing Rx-Linq 2.2.5.
Adding package 'Rx-Linq.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Linq.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Linq.2.2.5' to 'packages.config'
Successfully installed 'Rx-Linq 2.2.5' to xxx.iOS
  GET https://api.nuget.org/packages/rx-platformservices.2.2.5.nupkg
  OK https://api.nuget.org/packages/rx-platformservices.2.2.5.nupkg 22ms
Installing Rx-PlatformServices 2.2.5.
Adding package 'Rx-PlatformServices.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-PlatformServices.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-PlatformServices.2.2.5' to 'packages.config'
Successfully installed 'Rx-PlatformServices 2.2.5' to xxx.iOS
  GET https://api.nuget.org/packages/rx-main.2.2.5.nupkg
  OK https://api.nuget.org/packages/rx-main.2.2.5.nupkg 16ms
Installing Rx-Main 2.2.5.
Adding package 'Rx-Main.2.2.5', which only has dependencies, to project 'xxx.iOS'.
Adding package 'Rx-Main.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Main.2.2.5' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Main.2.2.5' to 'packages.config'
Successfully installed 'Rx-Main 2.2.5' to xxx.iOS
  GET https://api.nuget.org/packages/acr.deviceinfo.4.0.2.nupkg
  OK https://api.nuget.org/packages/acr.deviceinfo.4.0.2.nupkg 696ms
Installing Acr.DeviceInfo 4.0.2.
Adding package 'Acr.DeviceInfo.4.0.2' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Acr.DeviceInfo.4.0.2' to folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Acr.DeviceInfo.4.0.2' to 'packages.config'
Successfully installed 'Acr.DeviceInfo 4.0.2' to xxx.iOS
PM> Install-Package Acr.DeviceInfo
Attempting to gather dependency information for package 'Acr.DeviceInfo.4.0.2' with respect to project 'xxx', targeting '.NETPortable,Version=v4.5,Profile=Profile259'
Attempting to resolve dependencies for package 'Acr.DeviceInfo.4.0.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Acr.DeviceInfo.4.0.2'
Resolved actions to install package 'Acr.DeviceInfo.4.0.2'
Package 'Rx-Interfaces.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Interfaces.2.2.5' to 'packages.config'
Successfully installed 'Rx-Interfaces 2.2.5' to xxx
Package 'Rx-Core.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Core.2.2.5' to 'packages.config'
Successfully installed 'Rx-Core 2.2.5' to xxx
Package 'Rx-Linq.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Linq.2.2.5' to 'packages.config'
Successfully installed 'Rx-Linq 2.2.5' to xxx
Package 'Rx-PlatformServices.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-PlatformServices.2.2.5' to 'packages.config'
Successfully installed 'Rx-PlatformServices 2.2.5' to xxx
Adding package 'Rx-Main.2.2.5', which only has dependencies, to project 'xxx'.
Package 'Rx-Main.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Main.2.2.5' to 'packages.config'
Successfully installed 'Rx-Main 2.2.5' to xxx
Package 'Acr.DeviceInfo.4.0.2' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Acr.DeviceInfo.4.0.2' to 'packages.config'
Successfully installed 'Acr.DeviceInfo 4.0.2' to xxx
PM> Install-Package Acr.DeviceInfo
Attempting to gather dependency information for package 'Acr.DeviceInfo.4.0.2' with respect to project 'xxx.WinPhone', targeting 'WindowsPhoneApp,Version=v8.1'
Attempting to resolve dependencies for package 'Acr.DeviceInfo.4.0.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Acr.DeviceInfo.4.0.2'
Resolved actions to install package 'Acr.DeviceInfo.4.0.2'
Package 'Rx-Interfaces.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Interfaces.2.2.5' to 'packages.config'
Successfully installed 'Rx-Interfaces 2.2.5' to xxx.WinPhone
Package 'Rx-Core.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Core.2.2.5' to 'packages.config'
Successfully installed 'Rx-Core 2.2.5' to xxx.WinPhone
Package 'Rx-Linq.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Linq.2.2.5' to 'packages.config'
Successfully installed 'Rx-Linq 2.2.5' to xxx.WinPhone
Package 'Rx-PlatformServices.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-PlatformServices.2.2.5' to 'packages.config'
Successfully installed 'Rx-PlatformServices 2.2.5' to xxx.WinPhone
Adding package 'Rx-Main.2.2.5', which only has dependencies, to project 'xxx.WinPhone'.
Package 'Rx-Main.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Main.2.2.5' to 'packages.config'
Successfully installed 'Rx-Main 2.2.5' to xxx.WinPhone
Package 'Acr.DeviceInfo.4.0.2' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Acr.DeviceInfo.4.0.2' to 'packages.config'
Successfully installed 'Acr.DeviceInfo 4.0.2' to xxx.WinPhone
PM> Install-Package Acr.DeviceInfo
Attempting to gather dependency information for package 'Acr.DeviceInfo.4.0.2' with respect to project 'xxx.Droid', targeting 'MonoAndroid,Version=v6.0'
Attempting to resolve dependencies for package 'Acr.DeviceInfo.4.0.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Acr.DeviceInfo.4.0.2'
Resolved actions to install package 'Acr.DeviceInfo.4.0.2'
Package 'Rx-Interfaces.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Interfaces.2.2.5' to 'packages.config'
Successfully installed 'Rx-Interfaces 2.2.5' to xxx.Droid
Package 'Rx-Core.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Core.2.2.5' to 'packages.config'
Successfully installed 'Rx-Core 2.2.5' to xxx.Droid
Package 'Rx-Linq.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Linq.2.2.5' to 'packages.config'
Successfully installed 'Rx-Linq 2.2.5' to xxx.Droid
Package 'Rx-PlatformServices.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-PlatformServices.2.2.5' to 'packages.config'
Successfully installed 'Rx-PlatformServices 2.2.5' to xxx.Droid
Adding package 'Rx-Main.2.2.5', which only has dependencies, to project 'xxx.Droid'.
Package 'Rx-Main.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Main.2.2.5' to 'packages.config'
Successfully installed 'Rx-Main 2.2.5' to xxx.Droid
Package 'Acr.DeviceInfo.4.0.2' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Acr.DeviceInfo.4.0.2' to 'packages.config'
Successfully installed 'Acr.DeviceInfo 4.0.2' to xxx.Droid
PM> Install-Package Acr.DeviceInfo
Restoring packages for 'xxx.UWP'.
Failed to resolve all project references for 'xxx.UWP'. The package restore result for 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\xxx\xxx.UWP\xxx.UWP.csproj' may be incomplete.
Restoring packages for C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\xxx\xxx.UWP\project.json...
Detected package downgrade: Xamarin.Forms from 2.3.3.180 to 2.3.3.175 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms.Maps (>= 2.3.3.180) -> Xamarin.Forms (>= 2.3.3.180) 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)
Detected package downgrade: Xamarin.Forms from 2.3.3.180 to 2.3.3.175 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms.Maps (>= 2.3.3.180) -> Xamarin.Forms (>= 2.3.3.180) 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)
Detected package downgrade: Xamarin.Forms from 2.3.3.180 to 2.3.3.175 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms.Maps (>= 2.3.3.180) -> Xamarin.Forms (>= 2.3.3.180) 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)
Detected package downgrade: Xamarin.Forms from 2.3.3.180 to 2.3.3.175 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms.Maps (>= 2.3.3.180) -> Xamarin.Forms (>= 2.3.3.180) 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)
Detected package downgrade: Xamarin.Forms from 2.3.3.180 to 2.3.3.175 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms.Maps (>= 2.3.3.180) -> Xamarin.Forms (>= 2.3.3.180) 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)
Detected package downgrade: Xamarin.Forms from 2.3.3.180 to 2.3.3.175 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms.Maps (>= 2.3.3.180) -> Xamarin.Forms (>= 2.3.3.180) 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)
Detected package downgrade: Xamarin.Forms from 2.3.3.180 to 2.3.3.175 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms.Maps (>= 2.3.3.180) -> Xamarin.Forms (>= 2.3.3.180) 
 xxx.UWP (>= 1.0.0) -> Xamarin.Forms (>= 2.3.3.175)
Package restore completed successfully for 'xxx.UWP'.
Generating MSBuild file xxx.UWP.nuget.targets.
Generating MSBuild file xxx.UWP.nuget.props.
Successfully installed 'Acr.DeviceInfo 4.0.2' to xxx.UWP
PM> Install-Package Acr.DeviceInfo
Attempting to gather dependency information for package 'Acr.DeviceInfo.4.0.2' with respect to project 'xxx.Windows', targeting 'Windows,Version=v8.1'
Attempting to resolve dependencies for package 'Acr.DeviceInfo.4.0.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Acr.DeviceInfo.4.0.2'
Resolved actions to install package 'Acr.DeviceInfo.4.0.2'
Package 'Rx-Interfaces.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Interfaces.2.2.5' to 'packages.config'
Successfully installed 'Rx-Interfaces 2.2.5' to xxx.Windows
Package 'Rx-Core.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Core.2.2.5' to 'packages.config'
Successfully installed 'Rx-Core 2.2.5' to xxx.Windows
Package 'Rx-Linq.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Linq.2.2.5' to 'packages.config'
Successfully installed 'Rx-Linq 2.2.5' to xxx.Windows
Package 'Rx-PlatformServices.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-PlatformServices.2.2.5' to 'packages.config'
Successfully installed 'Rx-PlatformServices 2.2.5' to xxx.Windows
Adding package 'Rx-Main.2.2.5', which only has dependencies, to project 'xxx.Windows'.
Package 'Rx-Main.2.2.5' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Rx-Main.2.2.5' to 'packages.config'
Successfully installed 'Rx-Main 2.2.5' to xxx.Windows
Package 'Acr.DeviceInfo.4.0.2' already exists in folder 'C:\Users\garys\OneDrive\_AppDev\VisualStudio\Projects\xxx\packages'
Added package 'Acr.DeviceInfo.4.0.2' to 'packages.config'
Successfully installed 'Acr.DeviceInfo 4.0.2' to xxx.Windows
PM>

**Comment by aritchie** [comment]
I don't support winphone 8.x
