### ISSUE TITLE
System.Runtime.InteropServices.RuntimeInformation

### ISSUE THREAD

**Issue by straiser17** [aritchie/deviceinfo#24]
Hi,
When I try to instal your nuget I got this error:
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author

**Comment by aritchie** [comment]
Please read the readme file.  v5 is .net standard, not PCL.  If you want PCL, you can install v4.x from nuget which supports PCL profile 259.
