### ISSUE TITLE
Same Device ID on Windows 10 phones

### ISSUE THREAD

**Issue by jotprabh1** [aritchie/deviceinfo#25]
Hi Allan

I am facing a peculiar issue. I am trying to get the Device ID for Windows phones using ACR.DeviceInfo but I get the same Device ID on all the devices on which we install the app. Can you please check what's the problem.

I am just doing this in the PCL:
String imei = DeviceInfo.Hardware.DeviceId.ToString();

Thanks

**Comment by aritchie** [comment]
There is no problem that I can see.  I'm using the EasClientDeviceInformation.Id which is derived from the AppID, User SID, and machine ID which is exactly the value I'm looking for.  Perhaps there is a difference on the phone version, but this isn't something I can assist in testing.

If the end value ultimately doesn't serve your case, my suggestion is to override this one property on the hardware implementation with what you feel is more appropriate to your use case

**Comment by jotprabh1** [comment]
Thanks for the quick reply Allan. I have overridden it with ASHWID. But I'll suggest that you should use ASHWID instead of EasClientDeviceInformation because its a known problem with EasClientDeviceInformation that it provides the same Id for all Windows Phones.
