### ISSUE TITLE
Debug build, LinkAssemblies task failed unexpectedly

### ISSUE THREAD

**Issue by calbert52** [aritchie/deviceinfo#26]
Acr.DeviceInfo v5.0.3.
Xamarin 4.4.0.34
Xamarin.Android 7.2.0.7

6>The "LinkAssemblies" task failed unexpectedly.
6>System.UnauthorizedAccessException: Access to the path 'C:\Source\Mobile\ClocTrakMobile\ClocTrakMobile\ClocTrakMobile.Droid\obj\Debug\linkdst\Plugin.DeviceInfo.dll.config' is denied.

If I set Read-Only from true to false on the file, "obj\Debug\linkdst\Plugin.DeviceInfo.dll.config",  and run the project in debug, it will successfully deploy and run in debug. I need to keep setting the Read-Only attribute to false every time I run in debug.

**Comment by aritchie** [comment]
This doesn't really have anything to do with the library.  It sounds like an issue with VS locking things.  I'll remove the build artifacts in any case.
