### ISSUE TITLE
DeviceId on Android

### ISSUE THREAD

**Issue by softlion** [aritchie/deviceinfo#27]
The current deviceId is a hardware dependant deviceId. This is incorrect for 2 reasons:

1) as explained here: 
http://stackoverflow.com/questions/16869482/how-to-get-unique-device-hardware-id-in-android

2) it requires a dangerous right at install time (read phone number of callers)

Correct code as stated in the stackoverflow answer should be:
var androidId = Android.Provider.Settings.Secure.GetString(Context.ContentResolver,
                                                    Secure.AndroidId);

**Comment by aritchie** [comment]
This is a bit opinionated of a request.  When I originally wrote this library, it was the imei that I was after.  I'll look into making this configurable in a future release.
