### ISSUE TITLE
ios: Application Info should not block thread

### ISSUE THREAD

**Issue by softlion** [aritchie/deviceinfo#28]
The Init method must be async and must not wait the task completion source.

It should be up to the caller to decide to block a thread or not.

**Comment by aritchie** [comment]
This is the way it is for very good reason because variables in hardware tend to get called right away during app startup.  Most users don't have an async startup routine (async void doesn't count).  I also don't want the pain of documenting init as many users don't read.  The block isn't dangerous by any means as it doesn't call into anything that calculates things for long

**Comment by softlion** [comment]
I know that, but you definelty should document it as it will block the worker thread during thread switches.

Note that i removed all your libs from my apps. I found that their quality is not the one i expect. For example your settings library takes about 400ms of startup time. It's just a setting, so there should be something wrong in it. I also removed your deviceinfo lib. I'm glad you wrote it at first, but now it's too much pain having NetStandard and its 200 additional nugets plus Rx. Release builds are already too big.

**Comment by aritchie** [comment]
Does it make you feel good to send troll comments like this?  Does it offer anything constructive at all?  (nope)  All it does is make an overburdened OSS maintainer feel like crap.  I don't get paid for this and I certainly didn't ask you to use my libraries.  So why not just move on without bullshit comments like this?  You offer nothing of substance or offer any help besides a complaint.

**Comment by softlion** [comment]
Yes you are right. My feeling with your repo is now the same about you.

**Comment by modplug** [comment]
@softlion If you think it's that bad I guess you could **contribute** to the community with a PR instead of ranting to someone who spends their valuable spare time to help the community
