### ISSUE TITLE
DI?

### ISSUE THREAD

**Issue by weitzhandler** [aritchie/deviceinfo#30]
Hi,

Any plans to support DI?
Would be nice to have the static class as an interface implementer resolved by the IoC container.

**Comment by aritchie** [comment]
The whole plugin architecture is built around using DI.  Every implementation has an interface....  I use .Current/.Hardware/etc only to do the following:

```csharp
// autofac
var builder = new ContainerBuilder();
builder
    .Register(_ => DeviceInfo.Hardware)
    .As<IHardware>()
    .SingleInstance();
```

**Comment by weitzhandler** [comment]
Oh that's wonderful, thank you!

**Comment by weitzhandler** [comment]
Oh that's wonderful, thank you!
I didn't notice the `IHardware` interface.
