### ISSUE TITLE
Feature Request: Add an Observable if user Locks/Unlocks the Phone

### ISSUE THREAD

**Issue by escamoteur** [aritchie/deviceinfo#31]
I hink Locking/Unlockinbg of the Phone is a Device State too so it would be great if you could add

 Add an Observable if user Locks/Unlocks the Phone

All the best
Thomas

**Comment by aritchie** [comment]
I believe this is only "semi" possible in android.  It definitely isn't possible in iOS or UWP

**Comment by escamoteur** [comment]
What about this second answer? http://stackoverflow.com/questions/7888490/how-can-i-detect-screen-lock-unlock-events-on-the-iphone

Problem is my App plays back video and continues to do when the Phone is locked. So I was hoping we could add an event for situations like that

**Comment by aritchie** [comment]
I'm going to pass on this.  It seems fairly hacky.  It isn't something I need, nor is it something I want to support going forward.

**Comment by escamoteur** [comment]
Ok, no problem
