### ISSUE TITLE
Network State reports unreachable on IPV6 only network

### ISSUE THREAD

**Issue by jasoncouture** [aritchie/deviceinfo#32]
I would be happy to submit a pull request, the changes are very simple (Need to check for address of type AddressFamily.InterNetworkV6 in addition to InterNetwork), but the change is trivial.
As I state below, iOS is the biggest problem, but I couldn't for the life of me figure out what the random offline issue was for android, I assume it's the same, but may not be.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

I assume it affects all platforms, but its the biggest issue on iOS, my app was rejected because of failure to support ipv6 due to this issue.

 - [x] iOS
 - [x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of OS(s) listed above with issue
Any

## Version of this library
5.0.5

## Expected Behaviour
Network State should support ipv6 only networks, apple started requiring support for this in June 2016, Reference: https://developer.apple.com/support/ipv6/

## Actual Behavior
When connected to an ipv6 only network, network state is reported as unreachable. (No exception)

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
I would be happy to accept any PR you could provide.  I will look into this for the next release, but that could be a few weeks away.
