### ISSUE TITLE
Nuget cannot upgrade to Acr.DeviceInfo 5.0.5 get Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'

### ISSUE THREAD

**Issue by SOFSPEEL** [aritchie/deviceinfo#33]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [x] iOS
 - [] Android
 - [] UWP
 - [] .NET Standard

When trying to update to version Acr.DeviceInfo 5.0.5 from version 4.0.2.

![image](https://user-images.githubusercontent.com/1612646/31288830-60ea709e-aa7b-11e7-8030-d396d77c26a9.png)

I get the following error in Package Console:
Could not install package 'System.Runtime.InteropServices.RuntimeInformation 4.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

My setup is as follows:

Visual Studio Enterprise 2017 for Mac
Version 7.1.5 (build 2)
Installation UUID: 3734be81-7783-480e-9650-685bf880b427
Runtime:
	Mono 5.2.0.224 (d15-3/14f2c81) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 502000224

NuGet
Version: 4.3.0.2418

.NET Core
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/1.0.3/Sdks
SDK Version: 1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
Version: 1.5.5
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Apple Developer Tools
Xcode 9.0 (13247)
Build 9A235

Xamarin.iOS
Version: 11.0.0.0 (Visual Studio Enterprise)
Hash: 152b654a
Branch: xcode9
Build date: 2017-09-15 02:25:56-0400

Xamarin.Android
Version: 7.4.5.1 (Visual Studio Enterprise)
Android SDK: /Users/steve.fiedelberg/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		7.0   (API level 24)
		7.1   (API level 25)

SDK Tools Version: 
SDK Platform Tools Version: 26.0.0
SDK Build Tools Version: 26.0.1

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Xamarin.Mac
Version: 3.6.3.3 (Visual Studio Enterprise)

Xamarin Inspector
Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

Build Information
Release ID: 701050002
Git revision: 7afedcaef8e7542e70e3cf8f9bdb26938b8c0876
Build date: 2017-09-15 08:39:58-04
Xamarin addins: 3262aadf811a18c12eac6742532d052b0139a808
Build lane: monodevelop-lion-d15-3-xcode9

Operating System
Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by aritchie** [comment]
Make sure you're using .NET standard.
