### ISSUE TITLE
NuGet package installed successfully however does not appear in references list

### ISSUE THREAD

**Issue by pauldiston** [aritchie/deviceinfo#35]
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] .NET Standard

## Version of OS(s) listed above with issue
Android 8.0

## Version of this library
5.0.5

## Expected Behaviour
NuGet package is installed successfully and reference to Acr.DeviceInfo is listed in the references for the Android class library and the class library builds successfully.

## Actual Behavior
NuGet package **is** installed successfully, however reference to Acr.DeviceInfo is not listed in the references for the Android class library and the class library does not build successfully.
_The type or namespace name 'Acr' could not be found (are you missing a using directive or an assembly reference?)_

**Comment by aritchie** [comment]
The internal namespace and assembly name changed to Plugin.DeviceInfo a while back
