### ISSUE TITLE
Setting android:targetSdkVersion in AndroidManifest.xml breaks Acr.DeviceInfo.5.0.5

### ISSUE THREAD

**Issue by pauldiston** [aritchie/deviceinfo#36]
I have been trying to resolve a Xamarin Android installation issue and been setting the android:targetSdkVersion in AndroidManifest.xml, however when I do this, when Acr.DeviceInfo.5.0.5 tries to retrieve the Hardware info, I get an error as if the Phone State permission hadn't been specified.

Setting my Android project back to "Use Compile using SDK version" resolves this. I was setting the "Target Android version" to be either 24 (Android 7.0) or 26 (Android 8.0)

Do you know why this might be the case?

**Comment by aritchie** [comment]
The library hasn't been updated in a while to support the new SDK.  I do have a new release coming soon.
