### ISSUE TITLE
Not geting device IMEI on Android

### ISSUE THREAD

**Issue by salvad0rml** [aritchie/deviceinfo#37]
Hi,

I'm not geting my Device IMEI on Android. IDevice.DeviceID gives me an Hexadecimal string, that if I convert it to Decimal, it is not my Device IMEI.

My Code is:

IDevice Device = CrossDevice.Device;
String DeviceID = Device.DeviceId;

Thanks!!

**Comment by aritchie** [comment]
I'm not actually doing the IMEI anymore as it only really worked on android.

Please use the issue template in the future if you want help.
