### ISSUE TITLE
ACR Speech Recognition Plugin

### ISSUE THREAD

**Issue by gragra33** [aritchie/deviceinfo#40]
Sorry, but posting here as there is no way to post issues for ACR Speech Recognition Plugin - appears turned off.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [X] Android
 - [] tvOS
 - [] macOS
 - [X] .NET Standard
 - UWP IS NOT SUPPORTED DURING THE BETA PERIOD - ONLY PRs ARE WELCOME FOR NOW

## Version of Library

ACR Speech Recognition Plugin (latest)

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Unable to compile due to old missing Nuget package:

NuGet Package restore failed for project Samples.Droid: Unable to find version '7.5.0-alpha0029' of package 'reactiveui'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'https://api.nuget.org/v3/index.json'.
. Please see Error List window for detailed warnings and errors.	

Package Manager reports:

NuGet Package restore failed for project Samples.iOS: Unable to find version '7.5.0-alpha0029' of package 'reactiveui'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'https://api.nuget.org/v3/index.json'.
. Please see Error List window for detailed warnings and errors.
NuGet Package restore failed for project Samples.Droid: Unable to find version '7.5.0-alpha0029' of package 'reactiveui'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Package 'reactiveui.7.5.0-alpha0029' is not found on source 'https://api.nuget.org/v3/index.json'.
. Please see Error List window for detailed warnings and errors.
NU1603: Samples.UWP depends on reactiveui (>= 7.5.0-alpha0029) but reactiveui 7.5.0-alpha0029 was not found. An approximate best match of reactiveui 8.0.0-alpha0034 was resolved.

Following instructions from Package Manager Fails. Appears one of the nuget packages used is dependent  on that version and Nuget is unable to resolve.

Can you please update the project as requested by Package Manager.

Thanks.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment]
You don’t see issues because I don’t support the plugin anymore.
