### ISSUE TITLE
Uses Cirrious.CrossCore 1.0.0.0 instead of 4.0.0.0

### ISSUE THREAD

**Issue by Cybrosys** [aritchie/deviceinfo#7]
I'm currently using version 4 of MvvmCross and once I made that transition a lot of plugins broke because they're authored against CrossCore 1.0.0.0. The error I get during compilation is the following:
"The type 'Cirrious.CrossCore.Plugins.IMvxPluginLoader' is defined in an assembly that is not referenced. You must add a reference to assembly 'Cirrious.CrossCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e16445fd9b451819'."

Is this something that you're planning on fixing?

**Comment by aritchie** [comment]
When it isn't a beta any longer, I will update this plugin.  You can register deviceinfo manually and in fact, it is better to do it this way in any case.  In your PCL registration, you can call Mvx.RegisterSingleton(Acr.DeviceInfo.App); // hardware, connectivity, battery

**Comment by Cybrosys** [comment]
Ok, good to know. 

Thanks for telling me how to do it manually (now I can use other plugins as well).

I'm not using PCL but shared, so I added the registration calls in InitializePlatformServices override, but maybe that's the same thing (new to MvvmCross).
