### ISSUE TITLE
How to use the network plugin on ios?

### ISSUE THREAD

**Issue by MovTeam** [aritchie/deviceinfo#8]
Hi,

Thanks for sharing your wonderful plugin.

I am using the network plugin (utilities, version 1.4.0) with mvvmcross. In Android it works very perfectly (i added the permission on the manifest) but in iOS the plugin return a false when i use the "IsWifi".

Do i have to add any permission on iOS? Or doing any special thing?

Thanks again!

**Comment by aritchie** [comment]
Try the latest version.  I updated the reachability class internally.  It was likely an issue with iOS9
