### ISSUE TITLE
Does not contain a definition for "...."

### ISSUE THREAD

**Issue by dot-ly** [aritchie/deviceinfo#9]
Getting the following error in my Droid project when i compile. 

`Mobile.Droid.Resource.Dimension' does not contain a definition for`design_tab_min_width' (CS0117) (Mobile.Droid)

`Mobile.Droid.Resource.Dimension' does not contain a definition for`dialog_fixed_height_major' (CS0117) (Mobile.Droid)

Mobile.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_height_minor' (CS0117) (Mobile.Droid)

Mobile.Droid.Resource.Dimension' does not contain a definition for `dialog_fixed_width_major' (CS0117) (Mobile.Droid)

**Comment by cjschen** [comment]
Hey Ahmed! 

I'm having the same issue, wondering how you fixed it. 

Thanks

**Comment by dot-ly** [comment]
Hey @SijiaCodes , 

I closed this because it was opened it the wrong place. Re opened it here 

https://github.com/aritchie/userdialogs/issues/121

and never got around to fixing the issue. It's a android lib compatibility issue.

**Comment by cjschen** [comment]
Ah I see... thank you
